# Install Requirements

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!cp -r "/content/drive/MyDrive/AI dr nesma" /content/data
!pip install ultralytics

In [34]:
import os, cv2
import shutil
import random
import numpy as np
from PIL import Image, ImageFilter
from ultralytics import YOLO
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [4]:
os.listdir('./data')

['Benign melanocytic nevus',
 'Melanoma',
 'Wart',
 'Herpes Zoster',
 'Tinea capitis',
 'Tinea circinata',
 'Psoraisis',
 'Normal skin',
 'Tinea Versicolor',
 'Vitiligo',
 'Basal cell carcinoma',
 'Alopecia areata']

## `Split data into training testing validation`

In [5]:
source_dir = "./data"
dest_dir = "./Data-medical"
classes = os.listdir(source_dir)

os.makedirs(os.path.join(dest_dir, "train"), exist_ok=True)
os.makedirs(os.path.join(dest_dir, "val"), exist_ok=True)
os.makedirs(os.path.join(dest_dir, "test"), exist_ok=True)

# === AUGMENTATION FUNCTIONS ===
def add_noise(img):
    noise = np.random.normal(0, 25, img.shape).astype(np.uint8)
    noisy_img = cv2.add(img, noise)
    return noisy_img

def rotate_image(img, angle=15):
    h, w = img.shape[:2]
    matrix = cv2.getRotationMatrix2D((w//2, h//2), angle, 1)
    return cv2.warpAffine(img, matrix, (w, h))

def blur_image(img):
    return cv2.GaussianBlur(img, (5, 5), 0)

def apply_augmentations(img_path):
    img = cv2.imread(img_path)
    img_augmented = []
    img_augmented.append(img)
    img_augmented.append(add_noise(img))
    img_augmented.append(rotate_image(img, angle=random.choice([-15, 15])))
    img_augmented.append(blur_image(img))
    return img_augmented

# === ORGANIZE AND AUGMENT ===
for class_name in classes:
    os.makedirs(os.path.join(dest_dir, "train", class_name), exist_ok=True)
    os.makedirs(os.path.join(dest_dir, "val", class_name), exist_ok=True)
    os.makedirs(os.path.join(dest_dir, "test", class_name), exist_ok=True)

    class_images = [f for f in os.listdir(os.path.join(source_dir, class_name))
                    if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

    print(f"Organizing images for class: {class_name}...")
    train_files, temp_files = train_test_split(class_images, test_size=0.2, random_state=42)
    val_files, test_files = train_test_split(temp_files, test_size=0.5, random_state=42)
    print(f"Train: {len(train_files)}, Val: {len(val_files)}, Test: {len(test_files)}")

    # === COPY + AUGMENT ===
    for idx, file in enumerate(train_files):
        src = os.path.join(source_dir, class_name, file)

        # Apply augmentations
        augmented_imgs = apply_augmentations(src)

        for i, aug_img in enumerate(augmented_imgs):
            dst_filename = f"{os.path.splitext(file)[0]}_aug{i}.jpg"
            dst = os.path.join(dest_dir, "train", class_name, dst_filename)
            cv2.imwrite(dst, aug_img)

    # Just copy val/test images without augmentation
    for file in val_files:
        src = os.path.join(source_dir, class_name, file)
        dst = os.path.join(dest_dir, "val", class_name, file)
        shutil.copy(src, dst)

    for file in test_files:
        src = os.path.join(source_dir, class_name, file)
        dst = os.path.join(dest_dir, "test", class_name, file)
        shutil.copy(src, dst)

print("✅ Dataset organized and augmented successfully!")

Organizing images for class: Benign melanocytic nevus...
Train: 190, Val: 24, Test: 24
Organizing images for class: Melanoma...
Train: 230, Val: 29, Test: 29
Organizing images for class: Wart...
Train: 180, Val: 22, Test: 23
Organizing images for class: Herpes Zoster...
Train: 180, Val: 22, Test: 23
Organizing images for class: Tinea capitis...
Train: 107, Val: 13, Test: 14
Organizing images for class: Tinea circinata...
Train: 135, Val: 17, Test: 17
Organizing images for class: Psoraisis...
Train: 199, Val: 25, Test: 25
Organizing images for class: Normal skin...
Train: 146, Val: 18, Test: 19
Organizing images for class: Tinea Versicolor...
Train: 177, Val: 22, Test: 23
Organizing images for class: Vitiligo...
Train: 254, Val: 32, Test: 32
Organizing images for class: Basal cell carcinoma...
Train: 159, Val: 20, Test: 20
Organizing images for class: Alopecia areata...
Train: 136, Val: 17, Test: 17
✅ Dataset organized and augmented successfully!


## `Train model`

In [6]:
model = YOLO('/content/new_model.pt')
results = model.train(data='./Data-medical', epochs=100)

Ultralytics 8.3.159 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (NVIDIA A100-SXM4-40GB, 40507MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=./Data-medical, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=100, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=224, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/content/new_model.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0,

100%|██████████| 5.35M/5.35M [00:00<00:00, 336MB/s]


AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3146.6±938.1 MB/s, size: 680.4 KB)


train: Scanning /content/Data-medical/train... 8364 images, 0 corrupt: 100%|██████████| 8364/8364 [00:02<00:00, 3446.33it/s]


train: New cache created: /content/Data-medical/train.cache
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 1762.7±2002.3 MB/s, size: 937.5 KB)


val: Scanning /content/Data-medical/val... 261 images, 0 corrupt: 100%|██████████| 261/261 [00:02<00:00, 91.35it/s] 

val: /content/Data-medical/val/Alopecia areata/009315HB_fee391183f15cb4d62773032fe0be92d.jpg: corrupt JPEG restored and saved
val: /content/Data-medical/val/Alopecia areata/20220920_105729.jpg: corrupt JPEG restored and saved
val: /content/Data-medical/val/Alopecia areata/20221220_112958.jpg: corrupt JPEG restored and saved
val: /content/Data-medical/val/Alopecia areata/27982tn.jpg: corrupt JPEG restored and saved
val: /content/Data-medical/val/Alopecia areata/Alopecia_Areata_Beard-1200x628-Facebook.jpg: corrupt JPEG restored and saved
val: /content/Data-medical/val/Alopecia areata/alopecia-areata-wat-is-het-hoe-herken-je-het.jpg: corrupt JPEG restored and saved
val: /content/Data-medical/val/Alopecia areata/alopecia-barbae-v2_d.jpg: corrupt JPEG restored and saved
val: /content/Data-medical/val/Alopecia areata/alopeciaAreata_33309_lg.jpg: corrupt JPEG restored and saved
val: /content/Data-medical/val/Alopecia areata/alopeciaAreata_8336_lg (1).jpg: corrupt JPEG restored and saved
val: 

optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically... 
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 38 weight(decay=0.0), 39 weight(decay=0.0005), 39 bias(decay=0.0)
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to runs/classify/train
Starting training for 100 epochs...

      Epoch    GPU_mem       loss  Instances       Size


      1/100     0.834G      6.196         16        224:   3%|▎         | 14/523 [00:01<00:57,  8.83it/s]

      1/100     0.834G      6.138         16        224:   4%|▍         | 21/523 [00:03<01:14,  6.77it/s]
100%|██████████| 755k/755k [00:00<00:00, 47.4MB/s]
      1/100     0.861G       1.85         12        224: 100%|██████████| 523/523 [00:59<00:00,  8.82it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 19.11it/s]

                   all      0.881      0.996



      Epoch    GPU_mem       loss  Instances       Size


      2/100     0.936G     0.7029         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.09it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 48.32it/s]


                   all       0.87      0.989

      Epoch    GPU_mem       loss  Instances       Size


      3/100     0.955G     0.6318         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.20it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 64.97it/s]

                   all      0.797      0.992



      Epoch    GPU_mem       loss  Instances       Size


      4/100      1.06G     0.6558         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.19it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 43.46it/s]

                   all      0.889          1



      Epoch    GPU_mem       loss  Instances       Size


      5/100      1.08G     0.5793         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 53.30it/s]


                   all      0.858      0.996

      Epoch    GPU_mem       loss  Instances       Size


      6/100      1.12G     0.4992         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 38.08it/s]

                   all       0.82      0.989



      Epoch    GPU_mem       loss  Instances       Size


      7/100      1.17G     0.4668         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.13it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 50.87it/s]

                   all      0.843          1



      Epoch    GPU_mem       loss  Instances       Size


      8/100      1.28G     0.4107         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 40.84it/s]

                   all      0.862          1



      Epoch    GPU_mem       loss  Instances       Size


      9/100      1.39G     0.3654         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.30it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 62.65it/s]

                   all      0.858          1



      Epoch    GPU_mem       loss  Instances       Size


     10/100      1.41G     0.3432         12        224: 100%|██████████| 523/523 [00:58<00:00,  9.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 47.15it/s]

                   all      0.874      0.996



      Epoch    GPU_mem       loss  Instances       Size


     11/100      1.42G     0.3214         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.16it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 57.49it/s]

                   all      0.916          1



      Epoch    GPU_mem       loss  Instances       Size


     12/100      1.52G     0.2918         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 43.69it/s]

                   all      0.904      0.996



      Epoch    GPU_mem       loss  Instances       Size


     13/100      1.55G     0.3026         12        224: 100%|██████████| 523/523 [00:59<00:00,  8.80it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 34.29it/s]

                   all      0.885      0.996



      Epoch    GPU_mem       loss  Instances       Size


     14/100      1.61G     0.2643         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 48.25it/s]


                   all      0.877          1

      Epoch    GPU_mem       loss  Instances       Size


     15/100      1.66G     0.2568         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 35.35it/s]

                   all      0.851          1



      Epoch    GPU_mem       loss  Instances       Size


     16/100      1.77G     0.2454         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 34.48it/s]

                   all      0.889          1



      Epoch    GPU_mem       loss  Instances       Size


     17/100       1.8G     0.2294         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 63.32it/s]

                   all      0.893      0.996



      Epoch    GPU_mem       loss  Instances       Size


     18/100      1.87G     0.2278         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.22it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 65.62it/s]

                   all      0.843      0.996



      Epoch    GPU_mem       loss  Instances       Size


     19/100      1.92G     0.2255         12        224: 100%|██████████| 523/523 [00:58<00:00,  8.89it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 57.79it/s]

                   all      0.866      0.996



      Epoch    GPU_mem       loss  Instances       Size


     20/100      1.98G     0.2122         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 35.47it/s]

                   all      0.881          1



      Epoch    GPU_mem       loss  Instances       Size


     21/100      2.04G     0.1961         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 28.66it/s]

                   all      0.881          1



      Epoch    GPU_mem       loss  Instances       Size


     22/100       2.1G     0.1969         12        224: 100%|██████████| 523/523 [00:58<00:00,  9.00it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 66.19it/s]

                   all        0.9          1



      Epoch    GPU_mem       loss  Instances       Size


     23/100      2.16G     0.1816         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.26it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 51.45it/s]

                   all      0.897          1



      Epoch    GPU_mem       loss  Instances       Size


     24/100      2.23G     0.1848         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.08it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 42.26it/s]

                   all      0.889          1



      Epoch    GPU_mem       loss  Instances       Size


     25/100      2.28G     0.1854         12        224: 100%|██████████| 523/523 [00:58<00:00,  8.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 42.12it/s]

                   all      0.897          1



      Epoch    GPU_mem       loss  Instances       Size


     26/100      2.38G     0.1725         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.04it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 35.93it/s]

                   all      0.885      0.992



      Epoch    GPU_mem       loss  Instances       Size


     27/100      2.43G      0.155         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 46.21it/s]

                   all      0.923          1



      Epoch    GPU_mem       loss  Instances       Size


     28/100      2.54G     0.1677         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.16it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 67.99it/s]

                   all      0.912          1



      Epoch    GPU_mem       loss  Instances       Size


     29/100      2.55G     0.1572         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.18it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 69.18it/s]

                   all      0.893          1



      Epoch    GPU_mem       loss  Instances       Size


     30/100       2.6G      0.144         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 37.04it/s]

                   all      0.908      0.996



      Epoch    GPU_mem       loss  Instances       Size


     31/100      2.65G      0.138         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 63.34it/s]

                   all      0.939          1



      Epoch    GPU_mem       loss  Instances       Size


     32/100      2.72G     0.1473         12        224: 100%|██████████| 523/523 [00:55<00:00,  9.35it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 39.83it/s]

                   all      0.904      0.996



      Epoch    GPU_mem       loss  Instances       Size


     33/100      2.79G     0.1494         12        224: 100%|██████████| 523/523 [00:59<00:00,  8.84it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 71.07it/s]

                   all      0.881          1



      Epoch    GPU_mem       loss  Instances       Size


     34/100      2.87G     0.1404         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.08it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 37.39it/s]

                   all      0.881          1



      Epoch    GPU_mem       loss  Instances       Size


     35/100       2.9G     0.1305         12        224: 100%|██████████| 523/523 [00:55<00:00,  9.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 32.32it/s]

                   all       0.92          1



      Epoch    GPU_mem       loss  Instances       Size


     36/100      2.98G     0.1248         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 46.91it/s]

                   all      0.908          1



      Epoch    GPU_mem       loss  Instances       Size


     37/100      3.08G     0.1332         12        224: 100%|██████████| 523/523 [00:58<00:00,  8.94it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 48.39it/s]


                   all      0.885      0.996

      Epoch    GPU_mem       loss  Instances       Size


     38/100       3.1G     0.1289         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 61.17it/s]

                   all       0.92      0.996



      Epoch    GPU_mem       loss  Instances       Size


     39/100      3.14G     0.1189         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.09it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 52.72it/s]

                   all      0.904          1



      Epoch    GPU_mem       loss  Instances       Size


     40/100      3.25G     0.1204         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.09it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 40.11it/s]

                   all        0.9      0.996



      Epoch    GPU_mem       loss  Instances       Size


     41/100      3.26G     0.1093         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.27it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 36.39it/s]

                   all      0.904          1



      Epoch    GPU_mem       loss  Instances       Size


     42/100      3.32G     0.1142         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.11it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 59.33it/s]

                   all      0.877          1



      Epoch    GPU_mem       loss  Instances       Size


     43/100      3.37G     0.1148         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.11it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 41.19it/s]

                   all      0.908          1



      Epoch    GPU_mem       loss  Instances       Size


     44/100      3.45G     0.1055         12        224: 100%|██████████| 523/523 [00:58<00:00,  8.96it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 39.08it/s]

                   all      0.904          1



      Epoch    GPU_mem       loss  Instances       Size


     45/100      3.51G    0.09764         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.23it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 49.94it/s]

                   all      0.897      0.996



      Epoch    GPU_mem       loss  Instances       Size


     46/100      3.57G    0.09317         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.06it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 43.86it/s]

                   all      0.885          1



      Epoch    GPU_mem       loss  Instances       Size


     47/100      3.62G    0.09758         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.04it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 58.32it/s]

                   all        0.9          1



      Epoch    GPU_mem       loss  Instances       Size


     48/100      3.73G     0.0948         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.19it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 41.91it/s]

                   all      0.893          1



      Epoch    GPU_mem       loss  Instances       Size


     49/100      3.75G    0.09086         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 53.70it/s]

                   all      0.881      0.996



      Epoch    GPU_mem       loss  Instances       Size


     50/100      3.84G    0.08489         12        224: 100%|██████████| 523/523 [00:58<00:00,  8.94it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 39.13it/s]

                   all      0.897          1



      Epoch    GPU_mem       loss  Instances       Size


     51/100      3.88G    0.08405         12        224: 100%|██████████| 523/523 [00:58<00:00,  9.00it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 50.83it/s]

                   all      0.908          1



      Epoch    GPU_mem       loss  Instances       Size


     52/100      3.99G    0.08557         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 44.35it/s]

                   all        0.9      0.996



      Epoch    GPU_mem       loss  Instances       Size


     53/100         4G    0.08714         12        224: 100%|██████████| 523/523 [00:58<00:00,  9.00it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 51.84it/s]

                   all        0.9      0.996



      Epoch    GPU_mem       loss  Instances       Size


     54/100      4.06G    0.07866         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.24it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 42.03it/s]

                   all      0.908          1



      Epoch    GPU_mem       loss  Instances       Size


     55/100      4.12G    0.07572         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.20it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 44.23it/s]

                   all      0.885          1



      Epoch    GPU_mem       loss  Instances       Size


     56/100      4.17G     0.0756         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.11it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 40.10it/s]

                   all      0.877          1



      Epoch    GPU_mem       loss  Instances       Size


     57/100      4.28G    0.06938         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.14it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 45.10it/s]

                   all      0.897          1



      Epoch    GPU_mem       loss  Instances       Size


     58/100       4.3G    0.07217         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.09it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 42.58it/s]

                   all      0.904      0.996



      Epoch    GPU_mem       loss  Instances       Size


     59/100      4.37G    0.07148         12        224: 100%|██████████| 523/523 [00:58<00:00,  9.01it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 39.20it/s]

                   all        0.9      0.996



      Epoch    GPU_mem       loss  Instances       Size


     60/100      4.43G    0.06875         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.19it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 69.69it/s]

                   all      0.912      0.996



      Epoch    GPU_mem       loss  Instances       Size


     61/100       4.5G    0.06323         12        224: 100%|██████████| 523/523 [00:58<00:00,  8.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 45.03it/s]

                   all       0.92          1



      Epoch    GPU_mem       loss  Instances       Size


     62/100      4.54G    0.06501         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 48.07it/s]

                   all      0.908      0.996



      Epoch    GPU_mem       loss  Instances       Size


     63/100      4.61G    0.06195         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 48.50it/s]


                   all      0.916      0.996

      Epoch    GPU_mem       loss  Instances       Size


     64/100      4.67G    0.06799         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 37.30it/s]

                   all      0.916          1



      Epoch    GPU_mem       loss  Instances       Size


     65/100      4.73G       0.06         12        224: 100%|██████████| 523/523 [00:58<00:00,  8.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 43.28it/s]

                   all      0.916      0.996



      Epoch    GPU_mem       loss  Instances       Size


     66/100      4.79G    0.05705         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.13it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 44.39it/s]

                   all      0.916      0.996



      Epoch    GPU_mem       loss  Instances       Size


     67/100      4.85G    0.05264         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.26it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 44.19it/s]

                   all      0.927      0.996



      Epoch    GPU_mem       loss  Instances       Size


     68/100      4.92G    0.05268         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.25it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 72.49it/s]

                   all      0.908      0.996



      Epoch    GPU_mem       loss  Instances       Size


     69/100      4.99G    0.05243         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.22it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 63.70it/s]

                   all      0.893      0.996



      Epoch    GPU_mem       loss  Instances       Size


     70/100      5.05G    0.05004         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 40.48it/s]

                   all        0.9      0.996



      Epoch    GPU_mem       loss  Instances       Size


     71/100      5.11G     0.0484         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.23it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 45.10it/s]

                   all        0.9      0.996



      Epoch    GPU_mem       loss  Instances       Size


     72/100      5.16G    0.04779         12        224: 100%|██████████| 523/523 [00:58<00:00,  8.96it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 37.08it/s]

                   all      0.893      0.996



      Epoch    GPU_mem       loss  Instances       Size


     73/100      5.27G    0.04582         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.12it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 61.97it/s]

                   all      0.904      0.996



      Epoch    GPU_mem       loss  Instances       Size


     74/100      5.29G    0.04324         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 66.72it/s]


                   all      0.904      0.996

      Epoch    GPU_mem       loss  Instances       Size


     75/100      5.34G    0.04758         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.19it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 44.68it/s]

                   all      0.904      0.996



      Epoch    GPU_mem       loss  Instances       Size


     76/100      5.41G    0.04343         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 39.18it/s]

                   all      0.897      0.996



      Epoch    GPU_mem       loss  Instances       Size


     77/100      5.48G    0.03791         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.24it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 43.68it/s]

                   all      0.908      0.996



      Epoch    GPU_mem       loss  Instances       Size


     78/100      5.54G    0.04188         12        224: 100%|██████████| 523/523 [00:55<00:00,  9.44it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 49.56it/s]


                   all      0.904      0.992

      Epoch    GPU_mem       loss  Instances       Size


     79/100       5.6G    0.03521         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.31it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 39.17it/s]

                   all      0.908      0.992



      Epoch    GPU_mem       loss  Instances       Size


     80/100      5.67G    0.03725         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.15it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 48.05it/s]

                   all      0.912      0.992



      Epoch    GPU_mem       loss  Instances       Size


     81/100      5.74G    0.03686         12        224: 100%|██████████| 523/523 [00:55<00:00,  9.44it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 41.41it/s]

                   all      0.908      0.996



      Epoch    GPU_mem       loss  Instances       Size


     82/100       5.8G    0.03399         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.10it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 42.32it/s]

                   all      0.912      0.996



      Epoch    GPU_mem       loss  Instances       Size


     83/100      5.85G     0.0372         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.09it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 35.43it/s]

                   all        0.9      0.992



      Epoch    GPU_mem       loss  Instances       Size


     84/100      5.91G     0.0354         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.18it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 31.38it/s]

                   all        0.9      0.996



      Epoch    GPU_mem       loss  Instances       Size


     85/100      5.97G    0.03726         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.09it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 45.03it/s]

                   all      0.904      0.996



      Epoch    GPU_mem       loss  Instances       Size


     86/100      6.04G    0.03427         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.25it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 54.04it/s]

                   all      0.912      0.996



      Epoch    GPU_mem       loss  Instances       Size


     87/100      6.09G    0.03087         12        224: 100%|██████████| 523/523 [00:58<00:00,  8.93it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 40.55it/s]

                   all      0.912      0.996



      Epoch    GPU_mem       loss  Instances       Size


     88/100      6.16G    0.03249         12        224: 100%|██████████| 523/523 [00:55<00:00,  9.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 41.38it/s]

                   all      0.912      0.996



      Epoch    GPU_mem       loss  Instances       Size


     89/100      6.21G    0.02862         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.22it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 38.60it/s]

                   all      0.916      0.996



      Epoch    GPU_mem       loss  Instances       Size


     90/100      6.27G    0.02493         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.21it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 66.20it/s]

                   all       0.92      0.996



      Epoch    GPU_mem       loss  Instances       Size


     91/100      6.35G     0.0293         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 35.31it/s]

                   all      0.916      0.996



      Epoch    GPU_mem       loss  Instances       Size


     92/100      6.42G    0.02684         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.11it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 34.40it/s]

                   all      0.916      0.996



      Epoch    GPU_mem       loss  Instances       Size


     93/100      6.53G    0.03019         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.08it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 44.30it/s]

                   all      0.912      0.996



      Epoch    GPU_mem       loss  Instances       Size


     94/100      6.55G    0.02526         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.05it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 42.42it/s]

                   all      0.916      0.996



      Epoch    GPU_mem       loss  Instances       Size


     95/100      6.58G    0.02476         12        224: 100%|██████████| 523/523 [00:58<00:00,  8.91it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 70.82it/s]

                   all       0.92      0.996



      Epoch    GPU_mem       loss  Instances       Size


     96/100      6.64G    0.02602         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.34it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 43.33it/s]

                   all       0.92      0.996



      Epoch    GPU_mem       loss  Instances       Size


     97/100      6.71G    0.02636         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.17it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 61.59it/s]

                   all       0.92      0.996



      Epoch    GPU_mem       loss  Instances       Size


     98/100      6.77G    0.02241         12        224: 100%|██████████| 523/523 [00:57<00:00,  9.13it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 41.28it/s]

                   all      0.916      0.996



      Epoch    GPU_mem       loss  Instances       Size


     99/100      6.82G    0.02721         12        224: 100%|██████████| 523/523 [00:55<00:00,  9.43it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 46.45it/s]


                   all      0.912      0.996

      Epoch    GPU_mem       loss  Instances       Size


    100/100      6.89G    0.02376         12        224: 100%|██████████| 523/523 [00:56<00:00,  9.19it/s]
               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 35.69it/s]

                   all      0.912      0.996



100 epochs completed in 1.614 hours.
Optimizer stripped from runs/classify/train/weights/last.pt, 31.7MB
Optimizer stripped from runs/classify/train/weights/best.pt, 31.7MB

Validating runs/classify/train/weights/best.pt...
Ultralytics 8.3.159 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (NVIDIA A100-SXM4-40GB, 40507MiB)
YOLOv8m-cls summary (fused): 42 layers, 15,778,028 parameters, 0 gradients, 41.6 GFLOPs
train: /content/Data-medical/train... found 8364 images in 12 classes ✅ 
val: /content/Data-medical/val... found 261 images in 12 classes ✅ 
test: /content/Data-medical/test... found 266 images in 12 classes ✅ 


               classes   top1_acc   top5_acc: 100%|██████████| 9/9 [00:00<00:00, 11.62it/s]


                   all      0.939          1
Speed: 0.1ms preprocess, 1.1ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to runs/classify/train


## `Evaluation`

In [ ]:
# Evaluate on test set
metrics = model.val(data='./Data-medical', split='test')

In [8]:
print(f"Test Accuracy: {metrics.top1:.2f}%")
print(f"Test Accuracy (class): {metrics.top5:.2f}%")

Test Accuracy: 0.91%
Test Accuracy (class): 1.00%


In [35]:
def get_image_paths_and_labels(folder_path):
    image_paths = []
    labels = []
    for class_idx, class_name in enumerate(classes):
        class_dir = os.path.join(folder_path, class_name)
        if not os.path.exists(class_dir):
            continue
        for img_name in os.listdir(class_dir):
            image_paths.append(os.path.join(class_dir, img_name))
            labels.append(class_name)
    return image_paths, labels

# Get test images and labels
test_folder = 'Data-medical/test'
test_image_paths, true_labels = get_image_paths_and_labels(test_folder)

# Get predictions
pred_labels = []
for img_path in test_image_paths:
    results = model(img_path)  # Predict on single image
    names_dict = results[0].names
    probs = results[0].probs.data.tolist()
    pred_labels.append(names_dict[np.argmax(probs)])

# Convert to numpy arrays
true_labels = np.array(true_labels)
pred_labels = np.array(pred_labels)

le = LabelEncoder()
le.fit(true_labels)  # Ensure all true classes are captured
true_labels = le.transform(true_labels)
pred_labels = le.transform(pred_labels)


image 1/1 /content/Data-medical/test/Benign melanocytic nevus/772.jpg: 224x224 Benign melanocytic nevus 1.00, Melanoma 0.00, Basal cell carcinoma 0.00, Alopecia areata 0.00, Wart 0.00, 5.9ms
Speed: 3.7ms preprocess, 5.9ms inference, 0.1ms postprocess per image at shape (1, 3, 224, 224)

image 1/1 /content/Data-medical/test/Benign melanocytic nevus/102.jpg: 224x224 Benign melanocytic nevus 1.00, Melanoma 0.00, Basal cell carcinoma 0.00, Tinea circinata 0.00, Tinea Versicolor 0.00, 4.4ms
Speed: 1.2ms preprocess, 4.4ms inference, 0.0ms postprocess per image at shape (1, 3, 224, 224)

image 1/1 /content/Data-medical/test/Benign melanocytic nevus/1288.jpg: 224x224 Benign melanocytic nevus 1.00, Melanoma 0.00, Tinea circinata 0.00, Basal cell carcinoma 0.00, Tinea Versicolor 0.00, 4.4ms
Speed: 1.2ms preprocess, 4.4ms inference, 0.0ms postprocess per image at shape (1, 3, 224, 224)

image 1/1 /content/Data-medical/test/Benign melanocytic nevus/2.jpg: 224x224 Benign melanocytic nevus 1.00, Me

In [36]:
# Classification report
print("\nClassification Report:")
print(classification_report(true_labels, pred_labels, target_names=classes, digits=4))


Classification Report:
                          precision    recall  f1-score   support

Benign melanocytic nevus     0.8889    0.9412    0.9143        17
                Melanoma     0.8500    0.8500    0.8500        20
                    Wart     0.8750    0.8750    0.8750        24
           Herpes Zoster     0.9200    1.0000    0.9583        23
           Tinea capitis     0.9310    0.9310    0.9310        29
         Tinea circinata     0.8571    0.9474    0.9000        19
               Psoraisis     0.9167    0.8800    0.8980        25
             Normal skin     0.9524    0.8696    0.9091        23
        Tinea Versicolor     0.8667    0.9286    0.8966        14
                Vitiligo     0.9375    0.8824    0.9091        17
    Basal cell carcinoma     0.9394    0.9688    0.9538        32
         Alopecia areata     0.9000    0.7826    0.8372        23

                accuracy                         0.9060       266
               macro avg     0.9029    0.9047    0

In [37]:
# Confusion matrix
cm = confusion_matrix(true_labels, pred_labels)
print("\nConfusion Matrix:")
print(cm)


Confusion Matrix:
[[16  0  0  0  0  0  0  0  1  0  0  0]
 [ 0 17  0  1  1  0  0  0  0  0  0  1]
 [ 0  1 21  0  1  0  0  0  0  0  0  1]
 [ 0  0  0 23  0  0  0  0  0  0  0  0]
 [ 0  0  2  0 27  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 18  0  0  0  0  1  0]
 [ 0  0  0  1  0  0 22  1  0  1  0  0]
 [ 0  0  0  0  0  2  1 20  0  0  0  0]
 [ 1  0  0  0  0  0  0  0 13  0  0  0]
 [ 1  1  0  0  0  0  0  0  0 15  0  0]
 [ 0  0  0  0  0  1  0  0  0  0 31  0]
 [ 0  1  1  0  0  0  1  0  1  0  1 18]]


In [38]:
# Calculate per-class metrics
FP = cm.sum(axis=0) - np.diag(cm)  # False Positives
FN = cm.sum(axis=1) - np.diag(cm)  # False Negatives
TP = np.diag(cm)                   # True Positives

print("\nPer-class metrics:")
for i, class_name in enumerate(classes):
    precision = TP[i] / (TP[i] + FP[i]) if (TP[i] + FP[i]) > 0 else 0
    recall = TP[i] / (TP[i] + FN[i]) if (TP[i] + FN[i]) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    print(f"{class_name}:")
    print(f"  TP: {TP[i]}, FP: {FP[i]}, FN: {FN[i]}")
    print(f"  Precision: {precision:.4f}, Recall: {recall:.4f}, F1: {f1:.4f}\n")


Per-class metrics:
Benign melanocytic nevus:
  TP: 16, FP: 2, FN: 1
  Precision: 0.8889, Recall: 0.9412, F1: 0.9143

Melanoma:
  TP: 17, FP: 3, FN: 3
  Precision: 0.8500, Recall: 0.8500, F1: 0.8500

Wart:
  TP: 21, FP: 3, FN: 3
  Precision: 0.8750, Recall: 0.8750, F1: 0.8750

Herpes Zoster:
  TP: 23, FP: 2, FN: 0
  Precision: 0.9200, Recall: 1.0000, F1: 0.9583

Tinea capitis:
  TP: 27, FP: 2, FN: 2
  Precision: 0.9310, Recall: 0.9310, F1: 0.9310

Tinea circinata:
  TP: 18, FP: 3, FN: 1
  Precision: 0.8571, Recall: 0.9474, F1: 0.9000

Psoraisis:
  TP: 22, FP: 2, FN: 3
  Precision: 0.9167, Recall: 0.8800, F1: 0.8980

Normal skin:
  TP: 20, FP: 1, FN: 3
  Precision: 0.9524, Recall: 0.8696, F1: 0.9091

Tinea Versicolor:
  TP: 13, FP: 2, FN: 1
  Precision: 0.8667, Recall: 0.9286, F1: 0.8966

Vitiligo:
  TP: 15, FP: 1, FN: 2
  Precision: 0.9375, Recall: 0.8824, F1: 0.9091

Basal cell carcinoma:
  TP: 31, FP: 2, FN: 1
  Precision: 0.9394, Recall: 0.9688, F1: 0.9538

Alopecia areata:
  TP: 18

# Make Prediction For some Random Image

In [ ]:
model_predict = YOLO('models/new_model.pt')

In [ ]:
results = model_predict('D:\skin-Diseases-Detection-main\data\Tinea capitis\A-5-year-old-boy-with-a-large-kerion-celsi-before-treatment.png')

names_dict = results[0].names

probs = results[0].probs.data.tolist()

print(names_dict)
print(probs)

print(names_dict[np.argmax(probs)])